---
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Python ${{ matrix.python-version }}"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.10'
    strategy:
      matrix:
        python-version: ["3.10", "pypy3"]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv pre-commit PyYAML six toml cfgv click==8.0.4 distlib
filelock identify nodeenv platformdirs

      # Runs a set of commands using the runners shell
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
